name: "Build Docker Image"
description: "Builds a Docker image"
inputs:
  context:
    description: "Path to the Docker build context."
    required: true
  repository:
    description: "Repository name for the Docker image (defaults to current GitHub repository)."
    required: false
    default: ${{ github.repository }}
  domain:
    description: "The image's domain."
    required: true
  registry:
    description: Azure Registry to authenticate against.
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Setup docker image name
      run: |
        IMAGE_TAG="${{ github.ref_name }}"
        REPO_NAME=$(basename "${{ inputs.repository }}")
        DOCKER_IMAGE_NAME="${{ inputs.registry }}/${{ inputs.domain }}/${REPO_NAME}:${IMAGE_TAG}"
        echo "DOCKER_IMAGE_NAME=${DOCKER_IMAGE_NAME,,}" >> $GITHUB_ENV
        echo "docker_image_name=$DOCKER_IMAGE_NAME" >> $GITHUB_OUTPUT
      shell: bash

    - name: Build the docker image
      run: docker build ${{ inputs.context }} -t ${{ env.DOCKER_IMAGE_NAME }}
      shell: bash
