name: "Build and Push Helm Chart"
description: "Builds and publishes a Helm chart to the specified registry."
inputs:
  domain:
    description: "The chart's domain."
    required: true
  context:
    description: "Path to the helm directory."
    required: false
    default: "./helm"
  registry:
    description: "Azure Registry to authenticate against."
    required: true
outputs:
  chart:
    description: "Name of the Helm chart."
  ver:
    description: "Version of the Helm chart."
runs:
  using: "composite"
  steps:
    - name: Checkout helm chart repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Setup Helm
      uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3.5
      with:
        version: "v3.12.0"

    - name: Get chart's name
      id: set_chart_name
      run: |
        CHART=$(grep '^name:' Chart.yaml | awk '{print $2}')
        echo "chart=$CHART" >> $GITHUB_OUTPUT
      working-directory: ${{ inputs.context }}
      shell: bash

    - name: Get the chart's version
      id: set_chart_version
      run: |
        VER=$(grep '^version:' Chart.yaml | awk '{print $2}')
        echo "ver=$VER" >> $GITHUB_OUTPUT
      working-directory: ${{ inputs.context }}
      shell: bash

    - name: Package chart into tgz file
      run: |
        helm package . --dependency-update
      working-directory: ${{ inputs.context }}
      shell: bash

    - name: Publish chart to ACR
      run: |
        helm push ${{ steps.set-chart-name.outputs.chart }}-${{ steps.set-chart-version.outputs.ver }}.tgz \
          oci://${{ inputs.registry }}/helm/${{ inputs.domain }}
      working-directory: ${{ inputs.context }}
      shell: bash
