name: Update artifacts.json

on:
  pull_request:
    paths:
      - "actions/update-artifacts-file/**"

jobs:
  update-artifacts-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Update artifacts.json
        uses: ./actions/update-artifacts-file
        with:
          type: "helm"
          domain: infra
          artifact_name: "jenkins"
          artifact_tag: "5.0.17"
          registry: ${{ secrets.ACR_URL }}
          github_token: ${{ secrets.GH_PAT }}
          target_repo: "mapcolonies/helm-charts-test"
